<?php

namespace {$namespace}\Model;

/*
 * This model definition file has been automagically generated by the WebTarget nodejs
 * model gen script.
 *
 * @author Neil.Smith@WebTarget.co.uk
 * Created: {$created}
 *
 */

use {$namespace}\Model\Definitions\def{$table} as defs;
use Database\Abstracts;

class {$table} extends Abstracts\WTDBDefsAbstract {

    {$publics}


    public function exchangeArray(array $data) {

        {$exchangearray}

        parent::exchangeArray($data);
    }

}
