<?php

namespace Auth\Model\Definitions;

/**
 * This model definition file has been automagically 
 * generated by the WebTarget.co.uk model gen script.
 * http://www.github.com/WebTarget/ZF2modelGen
 *
 * @author Neil.Smith@WebTarget.co.uk
 * Created: 2/28/2017, 2:57:58 PM
 *
 */

class defUser {
    
	 const TABLENAME = 't_user'

}
