<?php

namespace {$namespace}\Model\Definitions;

use Database\Abstracts\WTDefsAbstract;

/**
 * This model definition file has been automagically generated by the WebTarget nodejs
 * model gen script.
 *
 * @author {$author}
 * Created: {$created}
 *
 */
class def{$table} extends WTDefsAbstract {

    {$consts}

}
