<?php

namespace ${namespace}\Model;


/*
 * This model definition file has been automagically generated by the WebTarget nodejs
 * model gen script.
 *
 * @author ${author}
 * Created: ${created}
 *
 */
 
use ${namespace}\Model\Definitions\def${table} as defs;

class ${table}Table extends \Database\Abstracts\WTDBAbstract {

}
