<?php

namespace ${namespace}\Model;

/*
 * This model definition file has been automagically 
 * generated by the WebTarget.co.uk model gen script.
 * http://www.github.com/WebTarget/ZF2modelGen
 *
 * @author ${author}
 * Created: ${created}
 *
 */
 
use ${namespace}\Model\Definitions\def${table} as defs;

class ${table}Table extends \Database\Abstracts\WTDBAbstract {

}
