<?php

namespace Sys\Model\Definitions;

/**
 * This model definition file has been automagically 
 * generated by the WebTarget.co.uk model gen script.
 * http://www.github.com/WebTarget/ZF2modelGen
 *
 * @author Neil.Smith@WebTarget.co.uk
 * Created: 2/28/2017, 4:03:18 PM
 *
 */

class defSettings {
    
	 const TABLENAME = 'ap_settings'
	 const ID = 'id'; 
	 const SMTP_ENABLE = 'smtp_enable'; 
	 const SMTP_HOST = 'smtp_host'; 
	 const SMTP_PORT = 'smtp_port'; 
	 const SMTP_AUTH = 'smtp_auth'; 
	 const SMTP_USERNAME = 'smtp_username'; 
	 const SMTP_PASSWORD = 'smtp_password'; 
	 const SMTP_SECURE = 'smtp_secure'; 
	 const UPLOAD_DIR = 'upload_dir'; 
	 const DATA_DIR = 'data_dir'; 
	 const DEFAULT_FROM_NAME = 'default_from_name'; 
	 const DEFAULT_FROM_EMAIL = 'default_from_email'; 
	 const DEFAULT_FORM_THEME_ID = 'default_form_theme_id'; 
	 const BASE_URL = 'base_url'; 
	 const FORM_MANAGER_MAX_ROWS = 'form_manager_max_rows'; 
	 const ADMIN_IMAGE_URL = 'admin_image_url'; 
	 const DISABLE_MACHFORM_LINK = 'disable_machform_link'; 
	 const CUSTOMER_ID = 'customer_id'; 
	 const CUSTOMER_NAME = 'customer_name'; 
	 const LICENSE_KEY = 'license_key'; 
	 const MACHFORM_VERSION = 'machform_version'; 
	 const ADMIN_THEME = 'admin_theme'; 
	 const ENFORCE_TSV = 'enforce_tsv'; 
	 const ENABLE_IP_RESTRICTION = 'enable_ip_restriction'; 
	 const IP_WHITELIST = 'ip_whitelist'; 
	 const ENABLE_ACCOUNT_LOCKING = 'enable_account_locking'; 
	 const ACCOUNT_LOCK_PERIOD = 'account_lock_period'; 
	 const ACCOUNT_LOCK_MAX_ATTEMPTS = 'account_lock_max_attempts'; 
	 const RECAPTCHA_SITE_KEY = 'recaptcha_site_key'; 
	 const RECAPTCHA_SECRET_KEY = 'recaptcha_secret_key'; 
	 const LDAP_ENABLE = 'ldap_enable'; 
	 const LDAP_TYPE = 'ldap_type'; 
	 const LDAP_HOST = 'ldap_host'; 
	 const LDAP_PORT = 'ldap_port'; 
	 const LDAP_ENCRYPTION = 'ldap_encryption'; 
	 const LDAP_BASEDN = 'ldap_basedn'; 
	 const LDAP_ACCOUNT_SUFFIX = 'ldap_account_suffix'; 
	 const LDAP_REQUIRED_GROUP = 'ldap_required_group'; 
	 const LDAP_EXCLUSIVE = 'ldap_exclusive'; 

}
