<?php

namespace Sys\Model;

/*
 * This model definition file has been automagically 
 * generated by the WebTarget.co.uk model gen script.
 * http://www.github.com/WebTarget/ZF2modelGen
 *
 * @author Neil.Smith@WebTarget.co.uk
 * Created: 2/28/2017, 4:03:18 PM
 *
 */
 
use Sys\Model\Definitions\defSettings as defs;

class SettingsTable extends \Database\Abstracts\WTDBAbstract {

}
