<?php

namespace Auth\Model;

/*
 * This model definition file has been automagically 
 * generated by the WebTarget.co.uk model gen script.
 * http://www.github.com/WebTarget/ZF2modelGen
 *
 * @author Neil.Smith@WebTarget.co.uk
 * Created: 2/28/2017, 2:56:58 PM
 *
 */

use Auth\Model\Definitions\defSettings as defs;
use Database\Abstracts;

class Settings extends Abstracts\WTDBDefsAbstract {

 

    public function exchangeArray(array $data) {


        parent::exchangeArray($data);
    }

}
